//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CST
    {
        public int CST_Id { get; set; }
        public int Subject_Id { get; set; }
        public int Section_Id { get; set; }
        public int Staff_Id { get; set; }
        public int Class_Id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
