//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent_Record
    {
        public int P_Id { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string DOB { get; set; }
        public string Address { get; set; }
        public string Cell_Number { get; set; }
        public string Gender { get; set; }
        public int Stud_Roll_Number { get; set; }
        public string Password { get; set; }
        public int Parent_Guardian { get; set; }
        public string Relation { get; set; }
    
        public virtual Student_Record Student_Record { get; set; }
        public virtual Relation Relation1 { get; set; }
    }
}
