//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvictusSchoolEntities : DbContext
    {
        public InvictusSchoolEntities()
            : base("name=InvictusSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<CST> CSTs { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Exam_Schedule> Exam_Schedules { get; set; }
        public virtual DbSet<Parent_Record> Parent_Records { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Attendence> Staff_Attendence { get; set; }
        public virtual DbSet<Student_Enrolment> Student_Enrolments { get; set; }
        public virtual DbSet<Student_Record> Student_Records { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
    }
}
