//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.CSTs = new HashSet<CST>();
            this.Sections = new HashSet<Section>();
            this.Staff_Attendence = new HashSet<Staff_Attendence>();
            this.Student_Enrolment = new HashSet<Student_Enrolment>();
        }
    
        public int Staff_Id { get; set; }
        public string Name { get; set; }
        public string Cell_Number { get; set; }
        public string Address { get; set; }
        public string CNIC { get; set; }
        public string Detail { get; set; }
        public int Designation_Id { get; set; }
        public int Salary { get; set; }
        public int Qualification_Id { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CST> CSTs { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Attendence> Staff_Attendence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Enrolment> Student_Enrolment { get; set; }
        public virtual Qualification Qualification1 { get; set; }
    }
}
