//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Record()
        {
            this.Attendences = new HashSet<Attendence>();
            this.Parent_Record = new HashSet<Parent_Record>();
            this.Student_Enrolment = new HashSet<Student_Enrolment>();
        }
    
        public int Stud_Id { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string DOB { get; set; }
        public string Roll_Number { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public System.DateTime Admission_Date { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendence> Attendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parent_Record> Parent_Record { get; set; }
        public virtual Result Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Enrolment> Student_Enrolment { get; set; }
    }
}
