//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolErp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Enrolment
    {
        public int Enrolment_Id { get; set; }
        public int Stud_ID { get; set; }
        public int Class_Id { get; set; }
        public int Section_Id { get; set; }
        public int Staff_Id { get; set; }
        public System.DateTime Session_Start { get; set; }
        public System.DateTime Session_End { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Student_Record Student_Record { get; set; }
    }
}
